project_id = "ufzhskookhsarjlijywh"

[functions.create-checkout]
verify_jwt = false

[functions.add-credits]
verify_jwt = true

[functions.send-order-notification]
verify_jwt = false

[functions.verify-payment]
verify_jwt = false

[functions.handle-new-order]
verify_jwt = false
